import type { TrackableCategory } from "../types";

export const huntersJournal: TrackableCategory = {
  name: "Hunter's Journal",
  description: "Bugs and creatures encountered across various areas of Pharloom.",
  hasGameModeSpecificItems: true,
  items: [
    {
      name: "Mossgrub",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["MossBone Crawler", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479075",
    },
    {
      name: "Massive Mossgrub",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["MossBone Crawler Fat", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480252",
    },
    {
      name: "Mossmir",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["MossBone Fly", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479076",
    },
    {
      name: "Moss Mother",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Mossbone Mother", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480309",
    },
    {
      name: "Aknid",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Aspid Collector", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479579",
    },
    {
      name: "Skull Scuttler",
      killsRequired: 35,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Goomba", 35] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479543",
    },
    {
      name: "Skullwing",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Goomba Bounce Fly", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479543",
    },
    {
      name: "Skull Brute",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Goomba Large", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479546",
    },
    {
      name: "Skull Tyrant",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Skull King", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480313",
    },
    {
      name: "Kilik",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Crawler", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479550",
    },
    {
      name: "Beastfly",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Flyer", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479544",
    },
    {
      name: "Savage Beastfly",
      killsRequired: 2,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Flyer Giant", 2] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480317",
    },
    {
      name: "Caranid",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Circler", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479547",
    },
    {
      name: "Vicious Caranid",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Circler Vicious", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479564",
    },
    {
      name: "Hardbone Hopper",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hopper", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479555",
    },
    {
      name: "Hardbone Elder",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hopper Giant", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480213",
    },
    {
      name: "Tarmite",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Spitter", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479058",
    },
    {
      name: "Mawling",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Roller", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479077",
    },
    {
      name: "Marrowmaw",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Thumper", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478224",
    },
    {
      name: "Hoker",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Spine Floater", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479570",
    },
    {
      name: "Flintbeetle",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Rock Roller", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478248",
    },
    {
      name: "Rhinogrund",
      killsRequired: 2,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Rhino", 2] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480179",
    },
    {
      name: "Gromling",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crypt Worm", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479078",
    },
    {
      name: "Grom",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Worm", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479080",
    },
    {
      name: "Bell Beast",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Beast", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480312",
    },
    {
      name: "Pilgrim Groveller",
      killsRequired: 35,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 03", 35] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479571",
    },
    {
      name: "Pilgrim Pouncer",
      killsRequired: 35,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 01", 35] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479551",
    },
    {
      name: "Pilgrim Hornfly",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 04", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479573",
    },
    {
      name: "Pilgrim Hulk",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 02", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479574",
    },
    {
      name: "Pilgrim Bellbearer",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Bell Thrower", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478044",
    },
    {
      name: "Winged Pilgrim",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Fly", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479552",
    },
    {
      name: "Elder Pilgrim",
      killsRequired: 5,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 05", 5] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479755",
    },
    {
      name: "Winged Pilgrim Bellbearer",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Bellthrower Fly", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478301",
    },
    {
      name: "Pilgrim Hiker",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Hiker", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479738",
    },
    {
      name: "Pilgrim Guide",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim StaffWielder", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479683",
    },
    {
      name: "Overgrown Pilgrim",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Moss Spitter", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479577",
    },
    {
      name: "Covetous Pilgrim",
      killsRequired: 2,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Rosary Pilgrim", 2] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478300",
    },
    {
      name: "Snitchfly",
      killsRequired: 4,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Rosary Thief", 4] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479000",
    },
    {
      name: "Lavalug",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Tar Slug", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479565",
    },
    {
      name: "Lavalarga",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Tar Slug Huge", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480236",
    },
    {
      name: "Smelt Shoveller",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dock Worker", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479553",
    },
    {
      name: "Flintstone Flyer",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dock Flyer", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479554",
    },
    {
      name: "Flintflame Flyer",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dock Bomber", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479566",
    },
    {
      name: "Smokerock Sifter",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Shield Dock Worker", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479567",
    },
    {
      name: "Deep Diver",
      killsRequired: 5,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dock Charger", 5] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480237",
    },
    {
      name: "Forebrothers Signis & Gron",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dock Guard Thrower", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480314",
    },
    {
      name: "Cragglite",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Small Crab", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480145",
    },
    {
      name: "Craggler",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Roof Crab", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478088",
    },
    {
      name: "Brushflit",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Fields Flock Flyers", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479560",
    },
    {
      name: "Fertid",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Fields Goomba", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479561",
    },
    {
      name: "Flapping Fertid",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Fields Flyer", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479562",
    },
    {
      name: "Fourth Chorus",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Golem", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480315",
    },
    {
      name: "Skarrlid",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter Tiny", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479558",
    },
    {
      name: "Skarrwing",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter Buzzer", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479557",
    },
    {
      name: "Skarr Scout",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter Child", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479559",
    },
    {
      name: "Skarr Stalker",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479563",
    },
    {
      name: "Spear Skarr",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter Fly", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479591",
    },
    {
      name: "Skarrgard",
      killsRequired: 2,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter Throw", 2] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=477962",
    },
    {
      name: "Gurr the Outcast",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter Trapper", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480316",
    },
    {
      name: "Last Claw",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Hunter Chief", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480483",
    },
    {
      name: "Skarrsinger Karmelita",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Hunter Queen", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479198",
    },
    {
      name: "Mite",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Mite", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479681",
    },
    {
      name: "Fluttermite",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Mitefly", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478974",
    },
    {
      name: "Mitemother",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Gnat Giant", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478975",
    },
    {
      name: "Dreg Catcher",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Farmer Catcher", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479685",
    },
    {
      name: "Silk Snipper",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Farmer Scissors", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478150",
    },
    {
      name: "Thread Raker",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Farmer Centipede", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478979",
    },
    {
      name: "Moorwing",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Vampire Gnat", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480340",
    },
    {
      name: "Wisp",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Wisp", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480438",
    },
    {
      name: "Burning Bug",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Farmer Wisp", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480440",
    },
    {
      name: "Father of the Flame",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Wisp Pyre Effigy", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480349",
    },
    {
      name: "Craw",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crow", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479679",
    },
    {
      name: "Tallcraw",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crowman", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479680",
    },
    {
      name: "Squatcraw",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crowman Dagger", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479682",
    },
    {
      name: "Craw Juror",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crowman Juror Tiny", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480485",
    },
    {
      name: "Tallcraw Juror",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crowman Juror", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480486",
    },
    {
      name: "Squatcraw Juror",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crowman Dagger Juror", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480487",
    },
    {
      name: "Crawfather",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crawfather", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480319",
    },
    {
      name: "Muckmaggot",
      killsRequired: 80,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Maggots", 80] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480190",
    },
    {
      name: "Slubberlug",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dustroach Pollywog", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478965",
    },
    {
      name: "Muckroach",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dustroach", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478264",
    },
    {
      name: "Bloatroach",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bloat Roach", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478737",
    },
    {
      name: "Roachcatcher",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Roachfeeder Short", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478261",
    },
    {
      name: "Roachfeeder",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Roachfeeder Tall", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478338",
    },
    {
      name: "Roachkeeper",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Roachkeeper", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478697",
    },
    {
      name: "Roachserver",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Roachkeeper Chef Tiny", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478991",
    },
    {
      name: "Disgraced Chef Lugoli",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Roachkeeper Chef", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480346",
    },
    {
      name: "Wraith",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Wraith", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478367",
    },
    {
      name: "Mothleaf Lagnia",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Drifter", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478738",
    },
    {
      name: "Miremite",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Goomba", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478966",
    },
    {
      name: "Swamp Squit",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Mosquito", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478721",
    },
    {
      name: "Spit Squit",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Mosquito Skinny", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480261",
    },
    {
      name: "Stilkin",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Muckman", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480206",
    },
    {
      name: "Stilkin Trapper",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Muckman Tall", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480238",
    },
    {
      name: "Groal the Great",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Shaman", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480345",
    },
    {
      name: "Barnak",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Barnacle", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478962",
    },
    {
      name: "Ductsucker",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Swamp Ductsucker", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480211",
    },
    {
      name: "Pond Skipper",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pond Skater", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478159",
    },
    {
      name: "Pondcatcher",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Fisher", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478161",
    },
    {
      name: "Shellwood Gnat",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Shellwood Gnat", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478983",
    },
    {
      name: "Wood Wasp",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Shellwood Wasp", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478160",
    },
    {
      name: "Splinter",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Stick Insect", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478980",
    },
    {
      name: "Splinterhorn",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Stick Insect Charger", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478169",
    },
    {
      name: "Splinterbark",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Stick Insect Flyer", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478186",
    },
    {
      name: "Sister Splinter",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Splinter Queen", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480324",
    },
    {
      name: "Phacia",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Flower Drifter", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478168",
    },
    {
      name: "Pollenica",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bloom Shooter", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478175",
    },
    {
      name: "Gahlia",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bloom Puncher", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478181",
    },
    {
      name: "Shrine Guardian Seth",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Seth", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480352",
    },
    {
      name: "Nyleth",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Flower Queen", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480353",
    },
    {
      name: "Furm",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bell Goomba", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478194",
    },
    {
      name: "Winged Furm",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bell Fly", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478195",
    },
    {
      name: "Pharlid",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Blade Spider", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479737",
    },
    {
      name: "Pharlid Diver",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Blade Spider Hang", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478232",
    },
    {
      name: "Shardillard",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Shell Fossil Mimic", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480162",
    },
    {
      name: "Sandcarver",
      killsRequired: 40,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Sand Centipede", 40] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480191",
    },
    {
      name: "Squirrm",
      killsRequired: 4,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Judge Child", 4] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479862",
    },
    {
      name: "Judge",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Judge", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479736",
    },
    {
      name: "Last Judge",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Last Judge", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480351",
    },
    {
      name: "Coral Furm",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Spike Goomba", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480363",
    },
    {
      name: "Driznit",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Conch Shooter", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478306",
    },
    {
      name: "Driznarga",
      killsRequired: 14,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Conch Shooter Heavy", 14] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480245",
    },
    {
      name: "Pokenabbin",
      killsRequired: 16,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Conch Stabber", 16] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480366",
    },
    {
      name: "Conchfly",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Conch Driller", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480369",
    },
    {
      name: "Great Conchfly",
      killsRequired: 2,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Conch Driller Giant", 2] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480335",
    },
    {
      name: "Crustcrawler",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Goombas", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480227",
    },
    {
      name: "Crustcrag",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Goomba Large", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480243",
    },
    {
      name: "Kai",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Swimmer Fat", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480231",
    },
    {
      name: "Spinebeak Kai",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Poke Swimmer", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480235",
    },
    {
      name: "Steelspine Kai",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Spike Swimmer", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480234",
    },
    {
      name: "Yuma",
      killsRequired: 16,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Swimmer Small", 16] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480233",
    },
    {
      name: "Yumama",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Big Jellyfish", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480232",
    },
    {
      name: "Karaka",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Warrior", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480229",
    },
    {
      name: "Kakri",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Flyer", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480230",
    },
    {
      name: "Yago",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Flyer Throw", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480228",
    },
    {
      name: "Karak Gor",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Brawler", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480225",
    },
    {
      name: "Alita",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Hunter", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480226",
    },
    {
      name: "Corrcrust Karaka",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Bubble Brute", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480224",
    },
    {
      name: "Crust King Khann",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral King", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480327",
    },
    {
      name: "Watcher at the Edge",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Coral Warrior Grey", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480326",
    },
    {
      name: "Voltvyrm",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Zap Core Enemy", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480336",
    },
    {
      name: "Drapefly",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Citadel Bat", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479013",
    },
    {
      name: "Drapelord",
      killsRequired: 4,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Citadel Bat Large", 4] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480263",
    },
    {
      name: "Drapemite",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Mite Heavy", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479004",
    },
    {
      name: "Giant Drapemite",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Understore Mite Giant", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480005",
    },
    {
      name: "Underworker",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Understore Small", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479512",
    },
    {
      name: "Underscrub",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 03 Understore", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479746",
    },
    {
      name: "Undersweep",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Staff Understore", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479837",
    },
    {
      name: "Underpoke",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Understore Poker", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479510",
    },
    {
      name: "Underloft",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Understore Thrower", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479511",
    },
    {
      name: "Undercrank",
      killsRequired: 4,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Understore Heavy", 4] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479836",
    },
    {
      name: "Envoy",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Pilgrim 01", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479897",
    },
    {
      name: "Choir Pouncer",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 01 Song", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479885",
    },
    {
      name: "Choir Hornhead",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 02 Song", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479887",
    },
    {
      name: "Choir Bellbearer",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 03 Song", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479882",
    },
    {
      name: "Choir Flyer",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim 04 Song", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479886",
    },
    {
      name: "Choir Elder",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pilgrim Stomper Song", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479906",
    },
    {
      name: "Choristor",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Pilgrim 03", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479883",
    },
    {
      name: "Reed",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Reed", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479880",
    },
    {
      name: "Grand Reed",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Reed Grand", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479918",
    },
    {
      name: "Choir Clapper",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Heavy Sentry", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480052",
    },
    {
      name: "Clawmaiden",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Handmaiden", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479899",
    },
    {
      name: "Memoria",
      killsRequired: 2,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Arborium Keeper", 2] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480239",
    },
    {
      name: "Minister",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Administrator", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480050",
    },
    {
      name: "Maestro",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Pilgrim Maestro", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480049",
    },
    {
      name: "Second Sentinel",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Knight", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480348",
    },
    {
      name: "Dreg Husk",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Threaded Husk", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480036",
    },
    {
      name: "Dregwheel",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Threaded Husk Spin", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480043",
    },
    {
      name: "Surgeon",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Pilgrim 02", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480409",
    },
    {
      name: "Mortician",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Creeper", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480040",
    },
    {
      name: "The Unravelled",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Conductor Boss", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480354",
    },
    {
      name: "Cogwork Underfly",
      killsRequired: 25,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Understore Automaton", 25] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480021",
    },
    {
      name: "Cogwork Hauler",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Understore Automaton EX", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480022",
    },
    {
      name: "Cogwork Crawler",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Automaton Goomba", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479962",
    },
    {
      name: "Cogworker",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Automaton Fly", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479938",
    },
    {
      name: "Cogwork Spine",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Automaton Fly Spike", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479963",
    },
    {
      name: "Cogwork Choirbug",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Automaton 01", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479961",
    },
    {
      name: "Cogwork Cleanser",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Automaton 02", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479968",
    },
    {
      name: "Cogwork Defender",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Automaton Shield", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479982",
    },
    {
      name: "Cogwork Clapper",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Automaton Ball", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479971",
    },
    {
      name: "Cogwork Dancers",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Clockwork Dancer", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480347",
    },
    {
      name: "Vaultborn",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Song Scholar Acolyte", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480008",
    },
    {
      name: "Lampbearer",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Lightbearer", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479994",
    },
    {
      name: "Scrollreader",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Scrollkeeper", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479991",
    },
    {
      name: "Vaultkeeper",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Scholar", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479999",
    },
    {
      name: "Trobbio",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Trobbio", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480343",
    },
    {
      name: "Tormented Trobbio",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Tormented Trobbio", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480344",
    },
    {
      name: "Penitent",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Slab Prisoner Leaper New", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479005",
    },
    {
      name: "Puny Penitent",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Slab Prisoner Fly New", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479006",
    },
    {
      name: "Freshfly",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Slab Fly Small Fresh", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480479",
    },
    {
      name: "Scabfly",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Slab Fly Small", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479008",
    },
    {
      name: "Guardfly",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Slab Fly Mid", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479007",
    },
    {
      name: "Wardenfly",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Slab Fly Large", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479011",
    },
    {
      name: "Broodmother",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Slab Fly Broodmother", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480338",
    },
    {
      name: "Driftlin",
      killsRequired: 20,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Peaks Drifter", 20] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479036",
    },
    {
      name: "Mnemonid",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crystal Drifter", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479043",
    },
    {
      name: "Mnemonord",
      killsRequired: 3,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Crystal Drifter Giant", 3] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480198",
    },
    {
      name: "Servitor Ignim",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Weaver Servitor", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478215",
    },
    {
      name: "Servitor Boran",
      killsRequired: 5,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Weaver Servitor Large", 5] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479041",
    },
    {
      name: "Winged Lifeseed",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Lifeblood Fly", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479858",
    },
    {
      name: "Plasmid",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Worm BlueBlood", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480146",
    },
    {
      name: "Plasmidas",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Bone Worm BlueTurret", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480331",
    },
    {
      name: "Plasmified Zango",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Blue Assistant", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479273",
    },
    {
      name: "Leaf Glider",
      killsRequired: 12,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Lilypad Fly", 12] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480218",
    },
    {
      name: "Leaf Roller",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Grass Goomba", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480217",
    },
    {
      name: "Pendra",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Hornet Dragonfly", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480223",
    },
    {
      name: "Pendragor",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Dragonfly Large", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480481",
    },
    {
      name: "Nuphar",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Lilypad Trap", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480222",
    },
    {
      name: "Cloverstag",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Cloverstag", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480221",
    },
    {
      name: "Palestag",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Cloverstag White", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480321",
    },
    {
      name: "Kindanir",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Grasshopper Child", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480215",
    },
    {
      name: "Verdanir",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Grasshopper Slasher", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480219",
    },
    {
      name: "Escalion",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Grasshopper Fly", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480220",
    },
    {
      name: "Clover Dancers",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Clover Dancer", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480322",
    },
    {
      name: "Shadow Creeper",
      killsRequired: 16,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Abyss Crawler", 16] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480134",
    },
    {
      name: "Shadow Charger",
      killsRequired: 6,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Abyss Crawler Large", 6] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480135",
    },
    {
      name: "Gloomsac",
      killsRequired: 15,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Gloomfly", 15] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480133",
    },
    {
      name: "Gargant Gloom",
      killsRequired: 4,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Gloom Beast", 4] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480132",
    },
    {
      name: "Void Tendrils",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Void Tendrils", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479744",
    },
    {
      name: "Void Mass",
      killsRequired: 8,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Black Thread Core", 8] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480418",
    },
    {
      name: "Summoned Saviour (Steel Soul Entry)",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Abyss Mass", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480310",
      onlyFoundInSteelSoulMode: true,
    },
    {
      name: "Wingmould",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["White Palace Fly", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480415",
    },
    {
      name: "Garpid",
      killsRequired: 30,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Centipede Trap", 30] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479626",
    },
    {
      name: "Imoba",
      killsRequired: 4,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Spike Lazy Flyer", 4] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479627",
    },
    {
      name: "Skrill",
      killsRequired: 10,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Surface Scuttler", 10] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479628",
    },
    {
      name: "Bell Eater",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Giant Centipede", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480350",
    },
    {
      name: "Huge Flea",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Giant Flea", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479122",
    },
    {
      name: "Shakra (Missable Entry)",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Shakra", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479822",
    },
    {
      name: "Garmond & Zaza (Missable Entry)",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Garmond_Zaza", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479361",
    },
    {
      name: "Lost Garmond",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Garmond", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480325",
    },
    {
      name: "Pinstress",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Pinstress Boss", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480337",
    },
    {
      name: "Widow",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Spinner Boss", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480323",
    },
    {
      name: "First Sinner",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["First Weaver", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480339",
    },
    {
      name: "Phantom",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Phantom", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480356",
    },
    {
      name: "Lace",
      killsRequired: 2,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Lace", 2] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480355",
    },
    {
      name: "Grand Mother Silk",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Silk Boss", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480342",
    },
    {
      name: "Lost Lace",
      killsRequired: 1,
      whichAct: 0,
      location: "",
      parsingInfo: { type: "journal", internalId: ["Lost Lace", 1] },
      mapLink: "https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=480341",
    },
  ],
};
