import type { TrackableCategory } from '../types';

export const wishes: TrackableCategory = {
  name: 'Wishes',
  description: 'Wishes',
  items: [
    // Wayfarer Wishes
    { name: 'The Lost Fleas', section: 'Wayfarer', whichAct: 1, completionPercent: 0, prereqs: [], location: 'The Marrow: Wish from Fleamaster Mooshka.', parsingInfo: [{ type: 'quest', internalId: 'Save the Fleas' }, { type: 'quest', internalId: 'Save the Fleas Pre' }], mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=477857' },
    { name: 'My Missing Courier', section: 'Wayfarer', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears after defeating Widow).', parsingInfo: { type: 'quest', internalId: 'Save Courier Short' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478207' },
    { name: 'Pinmaster\'s Oil', section: 'Wayfarer', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Pinmaster Plinney (accessible after sharpening your needle for the first time, and speaking to Pinmaster Plinney).', parsingInfo: { type: 'quest', internalId: 'A Pinsmiths Tools' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478211' },
    { name: 'The Wandering Merchant', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Save City Merchant' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478634' },
    { name: 'Rite of Rebirth', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Shellwood: Wish from Greyroot (accessible after completing the "Rite of the Pollip" wish and giving Twisted Bud to them).', parsingInfo: { type: 'quest', internalId: 'Wood Witch Curse' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478792' },
    { name: 'My Missing Brother', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears in ACT 2, provided that "My Missing Courier" wish is completed).', parsingInfo: { type: 'quest', internalId: 'Save Courier Tall' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478798' },
    { name: 'Infestation Operation', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Greymoor: Wish from Yarnaby (accessible after completing "Rite of Rebirth" wish).', parsingInfo: { type: 'quest', internalId: 'Doctor Curse Cure' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478814' },
    { name: 'Balm for the Wounded', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: Wish from Sherma (appears after you discover Whiteward, is also accessible by directly speaking to Sherma in Whiteward).', parsingInfo: { type: 'quest', internalId: 'Save Sherma' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478933' },
    { name: 'Trail\'s End', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Any Wishwall (appears after purchasing all maps from Shakra)', parsingInfo: { type: 'quest', internalId: 'Shakra Final Quest' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479237' },
    { name: 'The Lost Merchant', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall (appears after getting the Faydown Cloak and completing "The Wandering Merchant" and "Strengthening Songclave" wishes).', parsingInfo: { type: 'quest', internalId: 'Save City Merchant Bridge' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479244' },
    { name: 'Final Audience', section: 'Wayfarer', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall (appears after learning The Conductor\'s Melody, activating Second Sentinel (3 Cogheart Pieces), encountering a couple of Second Sentinel fight scenes in Choral Chambers).', parsingInfo: { type: 'quest', internalId: 'Song Knight' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479245' },
    { name: 'Fatal Resolve', section: 'Wayfarer', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall (appears after returning from The Abyss, is also accessible by visiting Pinstress\' Home).', parsingInfo: { type: 'quest', internalId: 'Pinstress Battle' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479443' },
    { name: 'Hero\'s Call', section: 'Wayfarer', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears after encountering a couple of Garmond and Zaza fight scenes).', parsingInfo: { type: 'quest', internalId: 'Garmond Black Threaded' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479445' },
    { name: 'Ecstasy of the End', section: 'Wayfarer', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears after finding all 30 Lost Fleas).', parsingInfo: { type: 'quest', internalId: 'Flea Games' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479641' },
    { name: 'Pain, Anguish, and Misery', section: 'Wayfarer', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Tormented Trobbio' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479370' },
    
    // Gather Wishes
    { name: 'Berry Picking', section: 'Gather', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Moss Grotto (Mosshome): Wish from Moss Druid.', parsingInfo: { type: 'quest', internalId: 'Mossberry Collection 1' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=477876' },
    { name: 'Rite of the Pollip', section: 'Gather', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Shellwood: Wish from Greyroot.', parsingInfo: { type: 'quest', internalId: 'Shell Flowers' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478173' },
    { name: 'Silver Bells', section: 'Gather', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears after defeating Widow).', parsingInfo: { type: 'quest', internalId: 'Shiny Bell Goomba' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478206' },
    { name: 'Alchemist\'s Assistant', section: 'Gather', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Wormways: Wish from Alchemist Zylotol (accessed after talking to him twice).', parsingInfo: { type: 'quest', internalId: 'Extractor Blue' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478482' },
    { name: 'Great Taste of Pharloom', section: 'Gather', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Choral Chambers: Wish from Loyal Mergwin.', parsingInfo: { type: 'quest', internalId: 'Great Gourmand' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478889' },
    { name: 'Advanced Alchemy', section: 'Gather', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Wormways: Wish from Alchemist Zylotol (accessed in ACT 3, provided that "Alchemist\'s Assistant" wish is completed).', parsingInfo: { type: 'quest', internalId: 'Extractor Blue Worms' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479278' },
    
    // Donate Wishes
    { name: 'Bone Bottom Repairs', section: 'Donate', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bone Bottom: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Building Materials' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=477884' },
    { name: 'A Lifesaving Bridge', section: 'Donate', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bone Bottom: On the Wishwall (appears after you reach Greymoor).', parsingInfo: { type: 'quest', internalId: 'Building Materials (Bridge)' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478220' },
    { name: 'Restoration of Bellhart', section: 'Donate', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears after defeating Widow, speaking to Pinmaster Plinney for the first needle upgrade, and selling a(ny) relic to Relic Seeker Scrounge).', parsingInfo: { type: 'quest', internalId: 'Belltown House Start' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478291' },
    { name: 'Bellhart\'s Glory', section: 'Donate', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears sometime after completing "Restoration of Bellhart" wish).', parsingInfo: { type: 'quest', internalId: 'Belltown House Mid' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478797' },
    { name: 'An Icon of Hope', section: 'Donate', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bone Bottom: On the Wishwall (appears in ACT 2).', parsingInfo: { type: 'quest', internalId: 'Building Materials (Statue)' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478839' },
    { name: 'Building up Songclave', section: 'Donate', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Songclave Donation 1' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478631' },
    { name: 'Strengthening Songclave', section: 'Donate', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Songclave Donation 2' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479239' },
    
    // Hunt Wishes
    { name: 'Garb of the Pilgrims', section: 'Hunt', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bone Bottom: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Pilgrim Rags' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=477885' },
    { name: 'Flexile Spines', section: 'Hunt', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Far Fields: Wish from Seamstress.', parsingInfo: { type: 'quest', internalId: 'Brolly Get' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=477964' },
    { name: 'Crawbug Clearing', section: 'Hunt', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears after defeating Widow).', parsingInfo: { type: 'quest', internalId: 'Crow Feathers' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478208' },
    { name: 'Volatile Flintbeetles', section: 'Hunt', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Bone Bottom: On the Wishwall (appears after you reach Greymoor).', parsingInfo: { type: 'quest', internalId: 'Rock Rollers' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478221' },
    { name: 'Roach Guts', section: 'Hunt', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Sinner\'s Roard: Wish from Crull and Benjin.', parsingInfo: { type: 'quest', internalId: 'Roach Killing' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478356' },
    { name: 'Fine Pins', section: 'Hunt', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Fine Pins' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478633' },
    { name: 'Cloaks of the Choir', section: 'Hunt', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall. (appears after completing "Buildung Up Songclave" and "Fine Pins" wishes).', parsingInfo: { type: 'quest', internalId: 'Song Pilgrim Cloaks' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478934' },
    { name: 'Broodfeast', section: 'Hunt', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Putrified Ducts: Wish from Runt.', parsingInfo: { type: 'quest', internalId: 'Huntress Quest' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478865' },
    
    // Grand Hunt Wishes
    { name: 'The Terrible Tyrant', section: 'Grand Hunt', whichAct: 1, completionPercent: 0, prereqs: ['Cling Grip'], location: 'Bone Bottom: On the Wishwall (appears after acquiring Cling Grip).', parsingInfo: { type: 'quest', internalId: 'Skull King' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478223' },
    { name: 'Savage Beastfly', section: 'Grand Hunt', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall (appears sometime in ACT 2, provided that Savage Beastfly in Hunter\'s March (Chapel of the Beast) is defeated).', parsingInfo: { type: 'quest', internalId: 'Beastfly Hunt' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478799' },
    { name: 'The Wailing Mother', section: 'Grand Hunt', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall (appears after completing "The Wandering Merchant" and "Strengthening Songclave" wishes).', parsingInfo: { type: 'quest', internalId: 'Broodmother Hunt' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479246' },
    { name: 'Dark Hearts', section: 'Grand Hunt', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Destroy Thread Cores' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479448' },
    { name: 'The Hidden Hunter', section: 'Grand Hunt', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Bellhart: On the Wishwall.', parsingInfo: { type: 'quest', internalId: 'Ant Trapper' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479446' },
    
    // Delivery Wishes
    { name: 'Bone Bottom Supplies', section: 'Delivery', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Couriers Tipp & Pill (accessible after completing "My Missing Courier" and "My Missing Brother" wishes).', parsingInfo: { type: 'quest', internalId: 'Courier Delivery Bonebottom' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478313' },
    { name: 'Pilgrim\'s Rest Supplies', section: 'Delivery', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Couriers Tipp & Pill (accessible after completing "My Missing Courier" and "My Missing Brother" wishes).', parsingInfo: { type: 'quest', internalId: 'Courier Delivery Pilgrims Rest' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478313' },
    { name: 'Fleatopia Supplies', section: 'Delivery', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Couriers Tipp & Pill (accessible after completing "My Missing Courier" and "My Missing Brother" wishes).', parsingInfo: { type: 'quest', internalId: 'Courier Delivery Fleatopia' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478313' },
    { name: 'Songclave Supplies', section: 'Delivery', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Couriers Tipp & Pill (accessible after completing "My Missing Courier" and "My Missing Brother" wishes).', parsingInfo: { type: 'quest', internalId: 'Courier Delivery Songclave' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478313' },
    { name: 'Queen\'s Egg', section: 'Delivery', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Couriers Tipp & Pill (accessible after completing "My Missing Courier" and "My Missing Brother" wishes).', parsingInfo: { type: 'quest', internalId: 'Courier Delivery Dustpens Slave' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479177' },
    { name: 'Liquid Lacquer', section: 'Delivery', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Couriers Tipp & Pill (accessible after completing "My Missing Courier" and "My Missing Brother" wishes).', parsingInfo: { type: 'quest', internalId: 'Courier Delivery Mask Maker' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479199' },
    { name: 'Survivor\'s Camp Supplies', section: 'Delivery', whichAct: 3, completionPercent: 0, prereqs: [], location: 'Bellhart: Wish from Couriers Tipp & Pill (accessible in ACT 3).', parsingInfo: { type: 'quest', internalId: 'Courier Delivery Fixer' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478313' },

    // Unique Wishes - Learn, Collect, Sprint, Witness, Steel
    { name: 'Bugs of Pharloom', section: 'Learn', whichAct: 1, completionPercent: 0, prereqs: [], location: 'Greymoor (Halfway Home): Wish from Nuu.', parsingInfo: { type: 'quest', internalId: 'Journal' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=478042' },
    { name: 'Silk and Soul', section: 'Collect', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Songclave: On the Wishwall (appears after defeating Lace, saving 25 Fleas and moving the caravan to Fleatopia, unlocking the Bellhome, completing all the available wishes, and talking to the Caretaker).', parsingInfo: { type: 'quest', internalId: 'Soul Snare Pre' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479243' },
    { name: 'Fastest in Pharloom', section: 'Sprint', whichAct: 3, completionPercent: 0, prereqs: ['Silk Soar'], location: 'Far Fields: Wish from Sprintmaster Swift.', parsingInfo: { type: 'quest', internalId: 'Sprintmaster Race' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479193' },
    { name: 'Passing of the Age', section: 'Witness', whichAct: 3, completionPercent: 0, prereqs: ['Silk Soar'], location: 'Putrified Ducts (Pale Lake): Interact with the riddle tablet.', parsingInfo: { type: 'quest', internalId: 'Mr Mushroom' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479142' },
    { name: 'A Vassal Lost (Steel Soul Wish)', section: 'Steel', whichAct: 2, completionPercent: 0, prereqs: [], location: 'Shellwood: (Steel Soul Only) Wish from Steel Seer Zi.', parsingInfo: { type: 'quest', internalId: 'Steel Sentinel Pt2' }, mapLink: 'https://mapgenie.io/hollow-knight-silksong/maps/pharloom?locationIds=479727' },
  ],
};